id: I84728EE5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:01:03+00:00'
last_modified: '2022-06-08T08:26:01.202753+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC274
  title: ཉིན་གཅིག་གི་ཆོ་འཕྲུལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    '5866':
      image_group_id: I2PD20339
      title: ''
      total_pages: 354
      order: 1
      base_file: 5866.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
