id: P009074
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC274
  title: ཉིན་གཅིག་གི་ཆོ་འཕྲུལ།
  author: ''
  volumes:
    500542f9e89047188b8d8736c7d3af1e:
      image_group_id: I2PD20339
      title: ''
      volume_number: 1
      total_pages: 354
      base_file: v001.txt
